export const toolParamNames = [
    "command",
    "path",
    "content",
    "context",
    "line_count",
    "regex",
    "file_pattern",
    "recursive",
    "action",
    "url",
    "coordinate",
    "text",
    "server_name",
    "tool_name",
    "arguments",
    "uri",
    "question",
    "result",
    "diff",
    "mode_slug",
    "reason",
    "line",
    "mode",
    "message",
    "cwd",
    "follow_up",
    "task",
    "size",
    "search",
    "replace",
    "use_regex",
    "ignore_case",
    // kilocode_change start
    "title",
    "description",
    "target_file",
    "instructions",
    "code_edit",
    // kilocode_change end
    "company_id",
    "employee_id",
    "department_id",
    "team_id",
    "action_item_id",
    "action_item_ids",
    "name",
    "vision",
    "mission",
    "owner_profile",
    "update_default_owner_profile",
    "role",
    "personality",
    "mbti_type",
    "personality_traits",
    "profile_image_url",
    "custom_attributes",
    "is_executive_manager",
    "companies",
    "company_updates",
    "employees",
    "employee_updates",
    "departments",
    "department_updates",
    "teams",
    "team_updates",
    "assignments",
    "employee_ids",
    "team_ids",
    "department_ids",
    "action_items",
    "action_item_updates",
    "employee",
    "department",
    "team",
    "include_archived",
    "name_contains",
    "args",
    "start_line",
    "end_line",
    "query",
    "web_search_type",
    "todos",
    "prompt",
    "image",
    "kind",
    "status_id",
    "status_ids",
    "owner_employee_id",
    "due_at",
    "priority",
    "custom_properties",
    "limit",
    "sop_name",
    "sop_variant",
    "sop_scope",
];
export const TOOL_DISPLAY_NAMES = {
    execute_command: "run commands",
    read_file: "read files",
    fetch_instructions: "fetch instructions",
    write_to_file: "write files",
    apply_diff: "apply changes",
    edit_file: "edit file", // kilocode_change: Morph fast apply
    search_files: "search files",
    list_files: "list files",
    list_code_definition_names: "list definitions",
    web_search: "search the web",
    browser_action: "use a browser",
    use_mcp_tool: "use mcp tools",
    access_mcp_resource: "access mcp resources",
    ask_followup_question: "ask questions",
    attempt_completion: "complete tasks",
    switch_mode: "switch modes",
    new_task: "create new task",
    insert_content: "insert content",
    search_and_replace: "search and replace",
    new_rule: "create new rule",
    report_bug: "report bug", // kilocode_change
    condense: "condense the current context window", // kilocode_change
    codebase_search: "codebase search",
    update_todo_list: "update todo list",
    run_slash_command: "run slash command",
    upsert_sop: "create or update SOP",
    generate_image: "generate images",
    create_company: "create company",
    update_company: "update company",
    create_employee: "create workplace employee",
    update_employee: "update workplace employee",
    create_department: "create department",
    update_department: "update department",
    create_team: "create team",
    update_team: "update team",
    delete_company: "request company deletion",
    assign_employee_to_team: "assign employee to team",
    assign_team_to_department: "assign team to department",
    archive_employee: "archive workplace employee",
    archive_team: "archive workplace team",
    archive_department: "archive workplace department",
    remove_employee_from_team: "remove employee from team",
    remove_team_from_department: "remove team from department",
    list_companies: "list companies",
    list_departments: "list departments",
    list_teams: "list teams",
    list_employees: "list employees",
    create_action_item: "create action item",
    update_action_item: "update action item",
    delete_action_item: "delete action item",
    list_action_items: "list action items",
};
// Define available tool groups.
export const TOOL_GROUPS = {
    read: {
        tools: [
            "read_file",
            "fetch_instructions",
            "search_files",
            "list_files",
            "list_code_definition_names",
            "codebase_search",
            "list_companies",
            "list_departments",
            "list_teams",
            "list_employees",
            "list_action_items",
        ],
    },
    edit: {
        tools: [
            "apply_diff",
            "edit_file", // kilocode_change: Morph fast apply
            "write_to_file",
            "insert_content",
            "search_and_replace",
            "new_rule", // kilocode_change
            "generate_image",
            "create_company",
            "update_company",
            "create_employee",
            "update_employee",
            "create_department",
            "update_department",
            "create_team",
            "update_team",
            "delete_company",
            "assign_employee_to_team",
            "assign_team_to_department",
            "archive_employee",
            "archive_team",
            "archive_department",
            "remove_employee_from_team",
            "remove_team_from_department",
            "create_action_item",
            "update_action_item",
            "delete_action_item",
            "upsert_sop",
        ],
    },
    browser: {
        tools: ["browser_action"],
    },
    web: {
        tools: ["web_search"],
    },
    command: {
        tools: ["execute_command"],
    },
    mcp: {
        tools: ["use_mcp_tool", "access_mcp_resource"],
    },
    modes: {
        tools: ["switch_mode", "new_task"],
        alwaysAvailable: true,
    },
};
// Tools that are always available to all modes.
export const ALWAYS_AVAILABLE_TOOLS = [
    "ask_followup_question",
    "attempt_completion",
    "switch_mode",
    "new_task",
    "web_search",
    "report_bug",
    "condense", // kilocode_Change
    "update_todo_list",
    "run_slash_command",
    "upsert_sop",
    "create_employee",
    "update_employee",
    "create_department",
    "update_department",
    "create_team",
    "update_team",
    "assign_employee_to_team",
    "assign_team_to_department",
    "archive_employee",
    "archive_team",
    "archive_department",
    "remove_employee_from_team",
    "remove_team_from_department",
    "create_action_item",
    "update_action_item",
    "delete_action_item",
    "list_action_items",
];
//# sourceMappingURL=tools.js.map